#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
$root = __DIR__;

use Symfony\Component\Console\Application;
use ShvetsGroup\CommentsExporter\Commands\ExportCommand;
use ShvetsGroup\CommentsExporter\Commands\ImportCommand;

$application = new Application();

$application->add(new ExportCommand($root));
$application->add(new ImportCommand($root));

$application->run();