#!/usr/bin/env php
<?php

/**
 * Load correct autoloader depending on install location.
 */
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}
$root = __DIR__;

use ShvetsGroup\CommentsExporter\Commands\ExportCommand;
use ShvetsGroup\CommentsExporter\Commands\ImportCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ExportCommand($root));
$application->add(new ImportCommand($root));

$application->run();